spring:
  datasource:
    url: jdbc:mysql://172.19.132.25:37734/ythbk?useSSL=false
    username: root
    password: hysz2022
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: MYSQLHIKARI
      connection-test-query: SELECT 1

